# Generated by Django 3.0.2 on 2020-01-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='nota_id',
        ),
    ]
