# Generated by Django 2.0 on 2020-01-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_remove_alumno_nota_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
