# Generated by Django 2.0 on 2020-01-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_delete_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('fecha_de_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion ')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['nombre'],
            },
        ),
    ]
