# Generated by Django 3.0 on 2020-01-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_alumno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
