# Generated by Django 3.0 on 2020-01-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_delete_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_notas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_de_materia', models.CharField(max_length=200)),
                ('n1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('n2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
