# Generated by Django 2.2.5 on 2020-02-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0008_nota_estudiante_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id_materias', models.AutoField(primary_key=True, serialize=False)),
                ('m1', models.CharField(max_length=200)),
                ('m2', models.CharField(max_length=200)),
                ('m3', models.CharField(max_length=200)),
            ],
        ),
    ]
