# Generated by Django 2.2.5 on 2020-02-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0009_materias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materias',
            options={'ordering': ['id_materias'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materia'},
        ),
    ]
