# Generated by Django 3.0.3 on 2020-02-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0010_auto_20200205_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materias',
        ),
    ]
