# Generated by Django 3.0.3 on 2020-02-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0012_materia_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profesor',
        ),
    ]
