# Generated by Django 3.0.4 on 2020-03-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0014_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenrGeneral',
            fields=[
                ('idgenr_general', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': ('Lista',),
                'verbose_name_plural': ('Listas',),
                'db_table': 'genr_general',
            },
        ),
    ]
