# Generated by Django 3.0.6 on 2020-05-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0015_genrgeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200)),
                ('edad', models.CharField(max_length=200)),
                ('foto', models.CharField(max_length=2)),
                ('correo', models.CharField(max_length=200)),
                ('sudonimo', models.CharField(max_length=200)),
            ],
        ),
    ]
