# Generated by Django 3.0.6 on 2020-05-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0016_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
