# Generated by Django 3.0.6 on 2020-05-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0017_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=50, verbose_name='Nombre de pais')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=20)),
                ('planta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50, verbose_name='ingrese la region')),
                ('temperatura', models.CharField(max_length=20)),
                ('plantas', models.CharField(max_length=20)),
                ('id_provinvia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200)),
                ('edad', models.CharField(max_length=200)),
                ('foto', models.CharField(max_length=2)),
                ('correo', models.CharField(max_length=200)),
                ('sudonimo', models.CharField(max_length=200)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Pais')),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Provincia')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Region')),
            ],
        ),
        migrations.AddField(
            model_name='pais',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Region'),
        ),
    ]
